spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:zxyspace}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false

# 日志配置
logging:
  level:
    root: WARN
    com.zxyspace: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN

# 服务器配置
server:
  port: ${PORT:8080}
  
# 用于生产环境的额外安全配置
security:
  require-ssl: true 