spring:
  datasource:
    url: jdbc:h2:mem:zxyspace_dev
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT配置
jwt:
  secret: your-secret-key-here
  expiration: 86400000 # 24小时

# 日志配置
logging:
  level:
    root: INFO
    com.zxyspace: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
